apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rj9v4cfov-java-quarkus 
  janus-idp.io/tekton: rj9v4cfov-java-quarkus
  backstage.io/kubernetes-id: rj9v4cfov-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rj9v4cfov-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml